### ISSUE TITLE
to do list detail view

### ISSUE THREAD

**Issue by ltalirz** [lsmo-epfl/discover-curated-cofs#1]
- [ ] show original structure as well (?)
 - add download buttons for 
   - [x] ~~cif file~~ Can be done via EXPLORE section
   - [ ] isotherms?
   - [ ] total energy convergence??
 - [x] figure out whether jsmol can work inside jupyter notebook
 - [x] switch back to locally hosted jsmol files
 - [x] fetch label from url parameters
 - [ ] add a tab with table of all properties

**Comment by ltalirz** [comment]
Issue with displaying structure in notebook:

```
Uncaught Error: Model 'JSMol' does not exist. This could be due to a widget
                     or a custom model not being registered before first usage.
```
... fixed!

**Comment by danieleongari** [comment]
This will be implemented in MatScreen
