### ISSUE TITLE
Suggestions for the entry page

### ISSUE THREAD

**Issue by danieleongari** [lsmo-epfl/discover-curated-cofs#3]
If possible, split the entry page in two columns:
- [x] right column has a list of cofs with the following entries:
`label, conventional name, reference structure, optimized structure w/DDEC charges`
where the first two come form the csv https://github.com/danieleongari/CoRE-COFs/blob/master/cof-frameworks.csv and the last two link to the breowseable structure (and all the connected calcualtions)
- [x] left column for the moment can have only Kh vs PE coloured by void fraction (use the `plasma` colorbar style, if available in bokeh, to be consistent with Fig 11 of the draft).

Note that there are charged COFs that are not optimized and not even included as a node in aiida, these should simply be listed but without links in the last two columns.

Moreover, I suggest to add 3 very clear buttons to:
 - [x] link to the GitHub page 
 - [ ] ~~automatically download the zip of the GitHub page~~ Leo: I don't think this is necessary
 - [x] download the zip with the all optimized structures from the archive (I added it as `cifs_cellopt.zip`)

**Comment by ltalirz** [comment]
Done!
