### ISSUE TITLE
table not showing for first view on materials cloud

### ISSUE THREAD

**Issue by ltalirz** [lsmo-epfl/discover-curated-cofs#5]
After starting the docker container, the first time you view the page on materials cloud it only shows the image for the scatter plot:
![Screenshot 2019-06-25 at 15 38 42](https://user-images.githubusercontent.com/1053245/60103185-74df7680-975f-11e9-88c9-157221a933c8.png)

When you reload the page, the table is shown as well
![Screenshot 2019-06-25 at 15 40 17](https://user-images.githubusercontent.com/1053245/60103257-8d4f9100-975f-11e9-9492-a90bdb366a24.png)

(also for subsequent visitors)

**Comment by danieleongari** [comment]
This problem is  not showing up anymore recently
